### PR TITLE
Added some features.

### PR DESCRIPTION
**Pull request by ypid**
Done: comments, unknown

Work in progress: sunrise/sunset #8 , open end #9

### CODE REVIEW

**Comment by ypid** [comment]
I opened this pull-request in that unfinished state (missing features) because I did all my changes to the API that I planned (except the location, which I will use to calculate the real sunrise and sunset). All other changes that I am going to make will be in the background of the library.

**Comment by ypid** [comment]
I just translated the demo.html to English and German so that a bigger audience can understand it.
I hope this does not break the original Russian version in any way.

**Comment by ypid** [comment]
I guess I am done for now. You can begin with your review if you want.

**Comment by ypid** [comment]
Do you want to maintain this project with all the changes I did to it or is it too deviated from your work and you don‘t agree with direction I am heading?

I have no problem with taking over this nice project, but I would like to hear your opinion.

**Comment by AMDmi3** [comment]
Honestly I currently don't have enough time to review it as your contribution is really large and I've lost track of its progress quite some time ago. It'd be easier if you split it into a set of topic branches so it could be discussed and merged feature-by-feature but I'm not sure I'm in right to ask for this due to my unresponsiveness.

**Comment by ypid** [comment]
Going over it feature by feature would be also time consuming for me. If that is OK with you I will take over maintenance.

PS: Our library is in [JOSM](http://josm.openstreetmap.de/ticket/9157) :smile:

**Pull request closed without merging**
